### ISSUE TITLE
Реорганизация API

### ISSUE THREAD

**Issue by StGeass** [Findoss/Duel#5]
## Перенос логики на клиент
Сама мысль переноса логики на сервер была абсолютно верной, однако тут ты слегка переборщил и перенёс на сервер даже то, что следовало оставить на клиенте.

Корень недопонимания тут возникает на шагах 3-4-5, где между итоговым и начальным состоянием существует промежуточное, которое с каждым своим изменением отправляется на клиент.

Выстраивается следующая цепочка состояний и событий:
 
1. Начальное состояние - Старая матрица
2. Перемена рун местами - новая, промежуточная матрица (swap)
3. Удаление ряда - новая, промежуточная матрица  (deleteCluster)
4. Смещение рун - новая, промежуточная матрица  (drop)
5. Добавление рун - новая, конечная матрица (refill)

Каждый из этих шагов предусматривает создание нового состояния, разницу между которыми ты шаришь для клиента отдельными командами в целях воспроизведения анимации.

Однако для приложения как такового существует только два состояния:

1. Начальное состояние - старая матрица
2. Конечное состояние - новая матрица

Где триггером перехода от одного к другому является выбор пользователем рун.

Все остальные состояния, это либо просто абстракция для перехода от одного состояния к другому (цепочка вызовов методов `delete().drop().refill()`), либо последовательные шаги анимации. 

При этом промежуточные шаги на уровне абстракции нам не нужны (в смысле не нужно где-либо хранить), т.к. сейв-поинт у нас только один, это конечное новое состояние. Подразумевается, что в БД или памяти мы не храним промежуточные состояния, а только итоговое, с новыми рунами.

Последовательность анимаций не дело сервера по нескольким причинам:
1. Сервер отвечает только за get/set операции, за возможные модификации данных при сохранении и отдаче, а так же за безопасную генерацию важных защищённых данных (у нас это сколько было нанесено урона/получено жизни/очков). Что и как с этим будет делать клиент - не его забота. Это важно так же, как и разделение бизнес логики с представлением.
2. Это загрязняет логику контроллера и запутывает её с каждой новой анимацией. Прибавь к текущему коду будущие анимации абилок, изменение очков и жизней, и в итоге получишь довольно адовый и сложный код для простых последовательностей действий.
3. Это навешивает лишние абстракции и посредники для исполнения простых команд, сейчас это `server.emit -> client.on -> add to queue` при каждом новом промежуточном состоянии, вместо одной последовательности `add to queue`.
4. Множественные последовательные `emit`'ы разных состояний одной сущности, это по сути анти-паттерн. Единственное оправдание такому - изменение этой сущности асинхронно. Однако у нас эти операции происходят синхронно (в контексте обработчика события).
5. Одна из важнейших задач анимации является сокрытие клиент-серверных задержек при медленном интернете или тупящем сервере. Даже при долгих запросах в 1-3 секунды, пользователь скорее всего не заметит задержки, благодаря тому, что в момент задержки ещё идёт анимация. Однако в нашем случае это работает ровно наоборот, он не только заметит задержку, но будет явно её ощущать, поскольку между каждым шагом анимации будет происходить задержка в n секунд.

### Что с этим делать

И так, допустим мы не будем делать множество последовательных эмитов, а будем делать только один, с конечным составом матрицы. Тогда мы сталкиваемся с проблемой, если есть только состояния A и B, то нам не на что опираться для составления анимации. Как быть?

Вариантов несколько:
1. Шарить за 1 emit все необходимые метаданные, на основе которых будет происходить анимация. По сути некий change log для текущего хода
2. Делать diff между A и B, воспроизводя цепочку изменений
3. Перенести всю логику анимации на клиент, дублировав логику работы с промежуточными значениями. По сути это то, что у тебя было до переноса всего на сервер, за некоторыми исключениями. Клиент может воспроизводить 90% анимацией без общения с сервером вообще, поскольку логика изменения матрицы всегда статична, и упирается только лишь в генерацию новых уникальных данных, таких как новый ряд рун. Таким образом валидация выбора руны, и её последующий swap (или fake swap, если валидация не проходит), а так же исчезновение рун и сдвиг оставшихся мы можем сделать параллельно с отправкой запроса на сервер, не дожидаясь от него каких-либо команд. 

Вариант №2 конечно же самый странный и сложный в реализации, а потому не нужен.
Вариант №1 звучит уже куда лучше, и легко реализуем с минимальным вмешательством в текущий код.
Вариант №3 во многом схож с вариантом №1: Он позволит полностью убрать логику команд анимации с серверной стороны и сократить количество подписок на стороне клиента, заменив все подписки на анимации всего одной, которая последовательно вызовет их внутри себя сама.

Главное отличие №1 и №3, это возможность совершения так называемого `optimistic update`, действия которое направлено на предугадывание ответа сервера, и совершения всех действий параллельно с запросом, чтобы сгладить возможную задержку в соединении.
№1 не даёт нам такой возможности, потому что логика работы с матрицей остаётся доступна только серверу, и для совершения анимации нам необходим change log, который мы получим только с ответом сервера.
№3 решает эту проблему и может начинать анимацию одновременно с запросом, а конечная анимация добавится в очередь позже, когда придёт ответ от сервера. Мы могли бы предугадывать даже начисление очков, если бы только там не было рандома.

Между 1 и 3 выбери сам. Я бы выбрал 3, но поскольку это чуть трудозатратнее, то не настаиваю. Если вдруг решишь делать, то просто создай рядом с client и server папку lib, и перенеси туда свои классы, которые импортируешь уже на клиенте и сервере через систему модулей.

## Пространство имён для событий и их декомпозиция

Сейчас у тебя существует порочная практика создания супер-обработчика, который внутри себя обрабатывает множество команд через switch. Лучше замени такие обработчики на множество маленьких, добавив командам свой namespace, который заодно будет указывать семантический контекст события: `socket.on('game/load', (param) => { ... })`.

Это позволит создавать более маленькие читабельные функции-контроллеры, которые можно будет при необходимости выносить в отдельные модули и покрывать тестами.

## Логирование

Думаю стоит отказаться от текущей системы логирования, которая мусорит в коде затрудняя его чтение. Отказаться или в сторону [нативного логгирования](https://socket.io/docs/logging-and-debugging/), или использования специального [декоратора](https://learn.javascript.ru/decorators), или [манки патчинга](https://gist.github.com/naholyr/4352358) метода `socket.on`.

**Comment by Findoss** [comment]
Я решил пойти от простого к сложному,

## Пространство имён для событий и их декомпозиция.
Все понятно.
## Логирование
  - нативное не подходит так как оно только в express и socket.io, a я хочу сам "править балом"
  - декораторы - новые функции обертки, значит в коде надо вызывать их, что я считаю крайне не удобно, так как это дополнительный слой, а когда мы захотим их убрать придётся все переписывать обратно или оставлять весь этот мусор.
  - манки патчинг - насколько я понял, это простое переопределение функции (что в js почему то не любят), вот это мне понравилось больше всего, так как мы вызываем функции как раньше и при необходимости можно спокойно выкинуть. Я вижу это как добавление файла `board.logs.js` в котором будет переопределение функций которые есть в классе.
## API
Вариант №2 - не имеет преимуществ что бы его рассматривать
Вариант №1 - это просто оптимизация того варианта что есть
Вариант №3 - тут мы вернем логику на клиентскую сторону, т.е. будет локальная копия мира. В теории предугадать можно все, у меня псевдорандом (рандом на основе зерна, зерно я  думал брать например id игры + соль). Если пойти дальше то сервер может заниматься только пересылкой действий игроков.
### Почему мне не нравиться вариант №3.
Наличие логики  на стороне клиента делает его менее безопасным. Мы можем просчитывать ходы или другие параметры при минимальном изменении кода.
Наличие логики на стороне клиента добавляет слой где взаимодействует логика в **перемешку** с отображением - этого я БОЮСЬ больше всего (желтый круг посередине). 
![2](https://user-images.githubusercontent.com/5212244/34719089-5b5dd39a-f54a-11e7-9f9b-b0da4132796a.jpg)

Что бы разделение было максимальным у классов были события на которые навешивались обработчики для постановки в очередь анимации и аудио. 
Вот наглядная схема ![1](https://user-images.githubusercontent.com/5212244/34719033-11924c46-f54a-11e7-8707-a3392d151593.jpg)
Это существенно упрощает но не дает чистоты. 

Поэтому когда я перешел к варианту №1, радовался о том что не надо заботиться на клиенте о валидации и встраивать все в игровой цикл, только отрисовка.

Пример 1 - свап рун, который  не приводит к линии.
*плюсы* Мы можем это предугадать, не отправлять на сервер и отобразить только на клиенте.
*минусы* Придется делать ряд проверок.

Пример 2 - показ подсказки.
*плюсы* Нам вообще не надо ходить на сервер за данными. 
*минусы* Вектор для преимущества. (выводя все подсказки или лучший вариант)

Итог, 
вариант №3 
самый хороший, но можно ли избежать сваливания кода логики и отображения в одну кучу?

вариант №1 
тормозит при медленном интернете или нагрузке на сервер, но прост и сильно разделяет код

**Comment by Findoss** [comment]
Я согласен что сервер не должен знать о анимации и прочих клиентских вещах, тогда есть смысл бОльшую часть убрать с сервера и перенеси на клиент, оптимизировать запросы, проверку которая относиться к клиенту (например возможность нажать на руну).

Есть метод о котором должен знать только 1 клиент, а остальные ничего. В таком случае при использовании метода внутри игрового цикла который мы предсказываем - предсказание сходит на нет.

Сейчас я попробую описать максимально "высоко" всю структуру игры, хотя если бы я мог то и вопросов бы не было. В таком случае я опишу идеальный итог который я вижу.

0. Игра имеет игровой цикл с основными событиями которые имеют конфигурацию, вот некоторые из них

Постоянные
- старт игры
- конец игры
- начало хода
- конец хода
и т.д.

Не постоянные
- урон по противнику
- смерть противника
- использование умений
- сбор рун
и т.д.

1. В игре методы привязываются к событиям
2. В игре методы могут привязываются к событиям других методов
3. В игре методы могут изменять игру
4. В игре свойства методов или сами методы могут быть доступны не всем игрокам
5. В игре методы могут изменять/дополнять поведение других методов
6. Клиент не знает о логике и за ответом (результатом) идет на сервер
7. Методы являются модулями что дает легко их вводить как в логику так и в отрисовку используя конфигурацию клиента и сервера.
