### ISSUE TITLE
 Организация функций для логики игры

### ISSUE THREAD

**Issue by Findoss** [Findoss/Duel#6]
наглядно  [рисовал тут](https://realtimeboard.com/app/board/o9J_kzjuYe0=/)

![image](https://user-images.githubusercontent.com/5212244/34720448-ce0bc71c-f54f-11e7-98dd-4e4ec17bf675.png)
```
before

// classes
import board
import player

game[id] = {
  new board
  new player
  ...
}

game[id].board.swap(coord, coord)
```
```
after

// data
import board
import player

// funcs
import ...
import core
import ...

game[id] = {
  new board
  new player
  ...
}

core.swap(game[id], coord, coord)
```

**Comment by StGeass** [comment]
Тебе в большей степени подходит первый вариант, учитывая что ты уже начал движение в сторону объектов и классов

**Comment by Findoss** [comment]
А как тогда быть со скилами? Ведь они могут использовать методы из разных классов
