### ISSUE TITLE
Логирование для дебага

### ISSUE THREAD

**Issue by Findoss** [Findoss/Duel#8]
С логами для дебага оказалось сложнее чем я думал, нативный это не то что я хотел бы, декораторы/обертки и манки патчинг не придумал как навесить на функции так что бы избавиться от массы console.log, особенно внутри callback функций.

https://github.com/Findoss/Duel/blob/namespace/server/index.js#L23-L28

**Comment by StGeass** [comment]
Да кстати, забыл тебе про это ответить

Манки патч и декорирование довольно похожи между собой, и то и другое это по сути обёртка вокруг конечной функции, которая добавляет middlеware в её поведение, но тут есть нюансы

Манки патч это переопределение функции с грубым добавлением кода-посредника, как у тебя это сделано для socket.io, в то время как декоратор это более гибкий паттерн, который может подмешивать разное поведение на лету к любым функциям, даже к анонимным, при этом поведение одного и того же декоратора может меняться благодаря тому, что он принимает дополнительные аргументы

Приведу примеры. Представь, что у нас есть декоратор logger который принимая множество аргументов пишет их в консоль. Манки патчинг по сути применим только лишь к socket.on или socket.emit, но декораторы применимы к чему угодно.

Так код
```
  socket.on('lobby/ready', () => {
    DEBUG.server && console.log('[.] generation board')
    DEBUG.server && console.log('[←] new board')
    DEBUG.server && console.log('[←] all suggestion')
    io.emit('generation', board.generationBoard())
    io.emit('suggestion', board.findMoves())
  })
```
Мы могли бы записать как
```
  socket.on('lobby/ready', logger(
    '[.] generation board', 
    '[←] new board',
    '[←] all suggestion'
   )(() => {
    io.emit('generation', board.generationBoard())
    io.emit('suggestion', board.findMoves())
  }))
```
Или так, если бы использовали траспиллер для нового синтаксиса декораторов
```
  socket.on('lobby/ready', @logger(
    '[.] generation board', 
    '[←] new board',
    '[←] all suggestion'
   )() => {
    io.emit('generation', board.generationBoard())
    io.emit('suggestion', board.findMoves())
  })
```

Разумеется, это не применимо с логам, которые должны вызываться по условиям. Но тут можно уже декорировать методы за которыми эти логи должны следовать (например, чтобы `board.deleteClusters` сам вызывал лог '[←] delete rune clusters'). При этом благодаря декоратору исходный код метода для этого трогать не надо.

Так что тут можно комбинировать три подхода:
1. Вынеси логирование в отдельную функцию, которую использовать в коде для манки патчинга и декорации. А так же там, где нельзя применить патч или декоратор. Простую функцию вроде `(msg) => DEBUG.server && console.log(msg)`.
2. Monkey patching для корневых методов вроде socket.on и socket.emit. Хотя в этом месте нативный дебаг вполне подойдёт.
3. Декораторы для анонимных функций и методов классов.

**Comment by Findoss** [comment]
Пример для преимущества не удачный просто, я там скорее хотел показать, что в отличии от патчинга его можно влепить вообще куда угодно

Более корректным примером это было бы при использовании внутри класса на методе

```
class Board {
  // ...
  @logger('[.] generation board')
  generationBoard () {
    // ...
  }
   // ...
}
```

В таком случае логи нигде в другом месте писать бы уже не пришлось

**Comment by Findoss** [comment]
Почему просто не добавить логирование в саму функцию? 
Потому что это не ее работа, она не должна этим заниматься.
